#!/bin/sh
#
# To hook this script run
#
# git config --local core.hooksPath .githooks
#

sed -i "" -e 's/DEVELOPMENT_TEAM = ""/DEVELOPMENT_TEAM = 523M9RF33S/' fake-location-app.xcodeproj/project.pbxproj
sed -i "" -e 's/com.example.fake-location-app/net.psytwo.fake-location-app/' fake-location-app.xcodeproj/project.pbxproj
