#!/bin/sh
#
# To hook this script run
#
# git config --local core.hooksPath .githooks
#

sed -i "" -e 's/DEVELOPMENT_TEAM = 523M9RF33S/DEVELOPMENT_TEAM = ""/' fake-location-app.xcodeproj/project.pbxproj
sed -i "" -e 's/net.psytwo.fake-location-app/com.example.fake-location-app/' fake-location-app.xcodeproj/project.pbxproj
