#!/bin/sh
#
# To hook this script run
#
# git config --local core.hooksPath .githooks
#

source .env
sed -i "" -e "s/DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM}/DEVELOPMENT_TEAM = \"\"/" fake-location-app.xcodeproj/project.pbxproj
sed -i "" -e "s/${BUNDLE_ID}/com.example.fake-location-app/" fake-location-app.xcodeproj/project.pbxproj
git add fake-location-app.xcodeproj/project.pbxproj
